import React from "react";
import Head from "next/head";
import Footer from "../Footer/Footer";
import Header from "../Header/Header";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="container text-center">{children}</section>
      <Footer />
    </div>
  );
};

export default Layout;
